# Generated by Django 2.2.2 on 2019-07-11 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=50)),
                ('ccode', models.IntegerField(default=0)),
                ('cnos', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='flag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='studentdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('centre', models.CharField(max_length=50)),
                ('sid', models.CharField(max_length=50)),
                ('sname', models.CharField(max_length=40)),
                ('skarma', models.IntegerField(default=200)),
                ('activity_1', models.IntegerField(default=25)),
                ('activity_2', models.IntegerField(default=25)),
                ('activity_3', models.IntegerField(default=25)),
                ('activity_4', models.IntegerField(default=25)),
                ('activity_5', models.IntegerField(default=25)),
                ('activity_6', models.IntegerField(default=25)),
                ('activity_7', models.IntegerField(default=25)),
                ('activity_8', models.IntegerField(default=25)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.courses')),
            ],
        ),
    ]
