# Generated by Django 2.2.2 on 2019-07-26 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdata',
            name='activity_1',
            field=models.IntegerField(default=25, verbose_name='Attendance'),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='activity_2',
            field=models.IntegerField(default=25, verbose_name='Classroom participation'),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='activity_3',
            field=models.IntegerField(default=25, verbose_name='Punctuality/ time management'),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='activity_4',
            field=models.IntegerField(default=25, verbose_name='Personal hygiene/ Grooming'),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='activity_5',
            field=models.IntegerField(default=25, verbose_name='Bed making'),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='activity_6',
            field=models.IntegerField(default=25, verbose_name='Participation in Swachha Bharat/ Swadhaan'),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='activity_7',
            field=models.IntegerField(default=25, verbose_name='Respect to teachers and others'),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='activity_8',
            field=models.IntegerField(default=25, verbose_name='Ethics and values'),
        ),
    ]
