# Generated by Django 2.2.2 on 2019-07-26 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0002_auto_20190726_1854'),
    ]

    operations = [
        migrations.DeleteModel(
            name='flag',
        ),
    ]
